/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Sources.Buyer;
import Sources.ChatHandle;
import Sources.Seller;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author grays
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    DefaultTableModel modelBuyer;
    DefaultTableModel modelSeller;
    List<Buyer> buyers = new ArrayList<>();
    List<Seller> sellers = new ArrayList<>();
    ChatHandle handle = new ChatHandle();

    private static String msg = "";

    public static String getMsg() {
        return msg;
    }

    public static void setMsg(String msg) {
        Home.msg = msg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        seller_fname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        seller_lname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        seller_area = new javax.swing.JTextField();
        svSeller = new javax.swing.JButton();
        svSeller1 = new javax.swing.JButton();
        svSeller2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        buyerFname = new javax.swing.JTextField();
        buyerLname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buyerArea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        svBuyer = new javax.swing.JButton();
        svSeller3 = new javax.swing.JButton();
        svSeller4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        buyTb = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        sellTb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat app");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Seller", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Frist Name");

        seller_fname.setForeground(new java.awt.Color(255, 255, 255));
        seller_fname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        seller_fname.setOpaque(false);
        seller_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seller_fnameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name");

        seller_lname.setForeground(new java.awt.Color(255, 255, 255));
        seller_lname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        seller_lname.setOpaque(false);
        seller_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seller_lnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Area");

        seller_area.setForeground(new java.awt.Color(255, 255, 255));
        seller_area.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        seller_area.setOpaque(false);
        seller_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seller_areaActionPerformed(evt);
            }
        });

        svSeller.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        svSeller.setForeground(new java.awt.Color(255, 255, 255));
        svSeller.setText("Register");
        svSeller.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 51), 2, true));
        svSeller.setContentAreaFilled(false);
        svSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svSellerActionPerformed(evt);
            }
        });

        svSeller1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        svSeller1.setForeground(new java.awt.Color(255, 255, 255));
        svSeller1.setText("Update");
        svSeller1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        svSeller1.setContentAreaFilled(false);
        svSeller1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svSeller1ActionPerformed(evt);
            }
        });

        svSeller2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        svSeller2.setForeground(new java.awt.Color(255, 255, 255));
        svSeller2.setText("Remove");
        svSeller2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 2, true));
        svSeller2.setContentAreaFilled(false);
        svSeller2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svSeller2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seller_area)
                            .addComponent(seller_fname)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(seller_lname))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(svSeller, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(svSeller1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(svSeller2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(seller_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(seller_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(seller_area, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(svSeller, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(svSeller2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(svSeller1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Buyer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setOpaque(false);

        buyerFname.setForeground(new java.awt.Color(255, 255, 255));
        buyerFname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        buyerFname.setOpaque(false);
        buyerFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyerFnameActionPerformed(evt);
            }
        });

        buyerLname.setForeground(new java.awt.Color(255, 255, 255));
        buyerLname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        buyerLname.setOpaque(false);
        buyerLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyerLnameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last Name");

        buyerArea.setForeground(new java.awt.Color(255, 255, 255));
        buyerArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        buyerArea.setOpaque(false);
        buyerArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyerAreaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Frist Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Area");

        svBuyer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        svBuyer.setForeground(new java.awt.Color(255, 255, 255));
        svBuyer.setText("Register");
        svBuyer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 102), 2, true));
        svBuyer.setContentAreaFilled(false);
        svBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svBuyerActionPerformed(evt);
            }
        });

        svSeller3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        svSeller3.setForeground(new java.awt.Color(255, 255, 255));
        svSeller3.setText("Update");
        svSeller3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        svSeller3.setContentAreaFilled(false);
        svSeller3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svSeller3ActionPerformed(evt);
            }
        });

        svSeller4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        svSeller4.setForeground(new java.awt.Color(255, 255, 255));
        svSeller4.setText("Remove");
        svSeller4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 2, true));
        svSeller4.setContentAreaFilled(false);
        svSeller4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svSeller4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(45, 45, 45)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buyerArea)
                            .addComponent(buyerLname)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(svBuyer, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(svSeller3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(svSeller4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(buyerFname)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buyerFname, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(buyerLname, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buyerArea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svBuyer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(svSeller3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(svSeller4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        buyTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Area"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        buyTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyTbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(buyTb);

        sellTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Area"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        sellTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellTbMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(sellTb);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seller_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seller_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seller_fnameActionPerformed

    private void seller_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seller_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seller_lnameActionPerformed

    private void seller_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seller_areaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seller_areaActionPerformed

    private void buyerFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyerFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyerFnameActionPerformed

    private void buyerLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyerLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyerLnameActionPerformed

    private void buyerAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyerAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyerAreaActionPerformed

    private void svSellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svSellerActionPerformed
       
        if(seller_fname.getText().trim().isEmpty() 
                && seller_lname.getText().trim().isEmpty() 
                && seller_area.getText().trim().isEmpty()){            
           JOptionPane.showMessageDialog(this,"Please enter all detail","Alert",JOptionPane.WARNING_MESSAGE); 
        }else if(seller_fname.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(this,"Please enter all detail","Alert",JOptionPane.WARNING_MESSAGE); 
        }else if(seller_area.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter all detail","Alert",JOptionPane.WARNING_MESSAGE); 
        }else if(seller_lname.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter all detail","Alert",JOptionPane.WARNING_MESSAGE); 
        }else{
        Seller b = new Seller();
        b.setCh(handle);
        b.setFirstName(seller_fname.getText());
        b.setLastName(seller_lname.getText());
        b.setArea(seller_area.getText());
        modelSeller = (DefaultTableModel) sellTb.getModel();
        sellers.add(b);
        System.out.println(sellers.get(0).getCh());
        modelSeller.addRow(new Object[]{b.getFirstName(), b.getLastName(), b.getArea()});
        for (Seller s : sellers) {
            System.out.println(s.getFirstName());
        }
        seller_fname.setText("");
        seller_lname.setText("");
        seller_area.setText("");
        }
    }//GEN-LAST:event_svSellerActionPerformed

    private void svBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svBuyerActionPerformed
        
        if(buyerFname.getText().trim().isEmpty() 
                && buyerLname.getText().isEmpty()
                && buyerArea.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter all detail","Alert",JOptionPane.WARNING_MESSAGE); 
        }else if(buyerFname.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter all detail","Alert",JOptionPane.WARNING_MESSAGE);
        }else if(buyerLname.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter all detail","Alert",JOptionPane.WARNING_MESSAGE);
        }else if(buyerArea.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter all detail","Alert",JOptionPane.WARNING_MESSAGE);
        }else{        
        Buyer b = new Buyer();
        b.setCh(handle);
        b.setFirstName(buyerFname.getText());
        b.setLastName(buyerLname.getText());
        b.setArea(buyerArea.getText());
        modelBuyer = (DefaultTableModel) buyTb.getModel();
        buyers.add(b);
        modelBuyer.addRow(new Object[]{b.getFirstName(), b.getLastName(), b.getArea()}); 
        buyerFname.setText("");
        buyerLname.setText("");
        buyerArea.setText("");
        }
    }//GEN-LAST:event_svBuyerActionPerformed
    public static ChatScreen scrn1;
    public static ChatScreen scrn2;
    private void sellTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellTbMouseClicked
        System.out.println("scren 2" + sellers.get(sellTb.getSelectedRow()));
        if (scrn2 == null) {
            msg = "";
            scrn2 = new ChatScreen(sellers.get(sellTb.getSelectedRow()));
            scrn2.setVisible(true);
        }
    }//GEN-LAST:event_sellTbMouseClicked

    private void buyTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyTbMouseClicked
        System.out.println("scren 1" + buyers.get(buyTb.getSelectedRow()));
        if (scrn1 == null) {
            msg = "";
            scrn1 = new ChatScreen(buyers.get(buyTb.getSelectedRow()));
            scrn1.setVisible(true);
        }
    }//GEN-LAST:event_buyTbMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
         ImageIcon icon = new ImageIcon("src/pic/chat.png");
         setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    private void svSeller1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svSeller1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_svSeller1ActionPerformed

    private void svSeller2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svSeller2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_svSeller2ActionPerformed

    private void svSeller3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svSeller3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_svSeller3ActionPerformed

    private void svSeller4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svSeller4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_svSeller4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable buyTb;
    private javax.swing.JTextField buyerArea;
    private javax.swing.JTextField buyerFname;
    private javax.swing.JTextField buyerLname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable sellTb;
    private javax.swing.JTextField seller_area;
    private javax.swing.JTextField seller_fname;
    private javax.swing.JTextField seller_lname;
    private javax.swing.JButton svBuyer;
    private javax.swing.JButton svSeller;
    private javax.swing.JButton svSeller1;
    private javax.swing.JButton svSeller2;
    private javax.swing.JButton svSeller3;
    private javax.swing.JButton svSeller4;
    // End of variables declaration//GEN-END:variables
}
